Repository SAP/abap-file-formats, pull requests merged in 2021-08, with the labels that each got.

#154 Add documentation to type specification
  doc/specification.md
Labels: documentation

#157 rm type in chkv
  file-formats/chkv/chkv.json
  file-formats/chkv/examples/z_aff_example_chkv.chkv.json
  file-formats/chkv/type/zif_aff_chkv_v1.intf.abap
Labels: enhancement

#156 Specification, see commit msg
  doc/specification.md
Labels: documentation

#162 add ddls to JSON validation script
  json-validator.py
Labels: enhancement

#158 Document Reusable Fields
  doc/specification.md
Labels: documentation

#170 Fix filename pattern in specification
  doc/specification.md
Labels: documentation

#174 remove global in filenames for CLAS
  doc/specification.md
  file-formats/clas/examples/zcl_aff_example.clas.abap
  file-formats/clas/format.md
Labels: documentation, enhancement, clas

#201 add LINKs of FUNC
  file-formats/fugr/README.md
Labels: documentation
