Repository SAP/abap-file-formats, pull requests merged in 2025-03, with the labels that each got.

#688 [AIFF] Add new object type AIFF
  file-formats/aiff/README.md
  file-formats/aiff/aiff-v1.json
  file-formats/aiff/examples/z_aff_example_aiff.aiff.json
  file-formats/aiff/type/zif_aff_aiff_v1.intf.abap
  file-formats/aiff/type/zif_aff_aiff_v1.intf.json
Labels: new-object, ux-review ready

#676 [SCP1] Added Fields, Removed Fields, Updated Fields, Title, Comment and Annotations added
  file-formats/scp1/examples/z_aff_example_scp1.scp1.json
  file-formats/scp1/scp1-v1.json
  file-formats/scp1/type/zif_aff_scp1_v1.intf.abap
Labels: ux-review ready

#690 Constraints for Defaults in JSON Files
  docs/json.md
Labels: documentation
